// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4xZPEkE0vBHTSoo0C4tGzE-y-Vyuv3bg',
    appId: '1:647535488041:web:40998f34dfcd41883e8038',
    messagingSenderId: '647535488041',
    projectId: 'habitsharenew',
    authDomain: 'habitsharenew.firebaseapp.com',
    storageBucket: 'habitsharenew.appspot.com',
    measurementId: 'G-ZL015V114K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvlw2PVWcgaaPYoIg9vIRaTJMmKnf7Um0',
    appId: '1:647535488041:android:aa1e1f44876f5b5b3e8038',
    messagingSenderId: '647535488041',
    projectId: 'habitsharenew',
    storageBucket: 'habitsharenew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuiqghgoZ6N-_lG3wZN0XnJlEdbibAMdQ',
    appId: '1:647535488041:ios:c74fc1260c63a6433e8038',
    messagingSenderId: '647535488041',
    projectId: 'habitsharenew',
    storageBucket: 'habitsharenew.appspot.com',
    iosBundleId: 'com.example.habitmonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuiqghgoZ6N-_lG3wZN0XnJlEdbibAMdQ',
    appId: '1:647535488041:ios:c74fc1260c63a6433e8038',
    messagingSenderId: '647535488041',
    projectId: 'habitsharenew',
    storageBucket: 'habitsharenew.appspot.com',
    iosBundleId: 'com.example.habitmonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4xZPEkE0vBHTSoo0C4tGzE-y-Vyuv3bg',
    appId: '1:647535488041:web:2ad5ca7686ec89793e8038',
    messagingSenderId: '647535488041',
    projectId: 'habitsharenew',
    authDomain: 'habitsharenew.firebaseapp.com',
    storageBucket: 'habitsharenew.appspot.com',
    measurementId: 'G-GVKQ9BER4R',
  );

}